name: Exaile CI

on: [push, pull_request]

jobs:

  lint:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install black
      - name: Check format
        run: make check_format

  test:
    strategy:
      matrix:
        imgtag:
          - debian-11
          - debian-stable
          - fedora-37
          - fedora-latest
          - ubuntu-20.04
          - ubuntu-rolling
    timeout-minutes: 4
    runs-on: ubuntu-latest
    container: ghcr.io/exaile/exaile-testimg:${{ matrix.imgtag }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and run tests
        # Exaile has tests for file permissions that fail when run as root, so
        # we de-escalate manually here.
        # This requires the image to already have a user named `exaile`, created
        # using e.g. `useradd -MN exaile`.
        run: |
          chown -R exaile .
          export HOME=/tmp/home
          su -m exaile -c "make BUILDDIR=/tmp/build test test_compile check-doc"

  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: [lint, test]
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y --no-install-recommends python3-gi
      - id: dist
        name: Create source dist archive
        run: |
          version=${GITHUB_REF#refs/*/}
          printf '::set-output name=version::%s\n' "${version}"
          make DIST_VERSION="$version" dist
          checksum=$(cd dist && sha256sum --tag *)
          printf '::set-output name=checksum::%s\n' "${checksum}"
      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version='${{ steps.dist.outputs.version }}'
          notes='```
          ${{ steps.dist.outputs.checksum }}
          ```'
          gh release create \
            "${version}" \
            "dist/exaile-${version}.tar.gz" \
            --draft \
            --title "Exaile ${version}" \
            --notes "${notes}"
